#!/bin/sh
REGEX='[0-9]+ offenses'

RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"

function display_text_message() {
  text=$1
  echo "${text}\n"
}


rubocop=$(rubocop)
echo $rubocop

rubocop=$(rubocop | tail -1)
echo $rubocop

echo "$rubocop" | grep -q REGEX

if [[ $? -eq 0 ]]; then
    echo "${RED} ❌ $2 errors have occurred ${NC} \n"
else
    echo "${GREEN} ✔ $2 Rubocop OK: $rubocop ${NC} \n"
    exit 1
fi
